### PR TITLE
Fixes #1 - Update OWNCA to comply with katello-certs-check

### LINKED ISSUE #1: Add Subject Alt Name on certificate and Key Usage extension on certificate for Key Encipherment
Now katello-certs-check utility has checks for Subject Alt Name on certificate and Key Usage extension on certificate for Key Encipherment.

### PR DESCRIPTION
**Pull request by chris1984**

### CODE REVIEW

**Comment by chris1984** [comment]
@iNecas can you review/merge when you get a chance please?

**Comment by ntkathole** [comment]
@chris1984 failed at ./generate-crt.sh satellite-hostname
```
Enter pass phrase for ./private/cakey.crt:
./<satellite_hostname>/<satellite_hostname>.req: No such file or directory
140091101169552:error:02001002:system library:fopen:No such file or directory:bss_file.c:402:fopen('./<satellite_hostname>/<satellite_hostname>.req','r')
140091101169552:error:20074002:BIO routines:FILE_CTRL:system lib:bss_file.c:404:
```

**Comment by chris1984** [comment]
@ntkathole ah ok me cleaning up the file name messed it up, ill revert that part back.

**Comment by chris1984** [comment]
@ntkathole updated.

**Comment by ntkathole** [comment]
@chris1984 still the same issue... I think the culprit is removing blank lines from generate-crt.sh. When I added those blank lines it worked. 

but katello-certs-check failed two checks
```
Checking Subject Alt Name on certificate[FAIL]
The /root/ownca/satellite/satellite.crt does not contain a Subject Alt Name
Checking Key Usage extension on certificate for Key Encipherment[FAIL]
The /root/ownca/satellite/satellite.crt does not allow for the 'Digital Signature' key usage

```

**Comment by chris1984** [comment]
@ntkathole ready for testing, that should fix it. I had to add some magic to the scripts to make it work correctly. Since just making changes to the openssl.cnf did not work and prevented the CA from being generated.

**Comment by ntkathole** [comment]
`# ./generate-ca.sh `
```
Error Loading request extension section v3_req
140611815008144:error:22097069:X509 V3 routines:DO_EXT_NCONF:invalid extension string:v3_conf.c:140:name=subjectAltName,section=@alt_names
140611815008144:error:22098080:X509 V3 routines:X509V3_EXT_nconf:error in extension:v3_conf.c:95:name=subjectAltName, value=@alt_names
```

**Review by ntkathole — COMMENTED** [review]
ACK! looks good :+1:

**Comment by chris1984** [comment]
@iNecas tested and working according to @ntkathole can I get a merge please?

**Pull request merged**
